### ISSUE TITLE
Troubles on Windows 7

### ISSUE THREAD

**Issue by SN902** [jdm/tinyfiledialogs-rs#36]
Application asks for "api-ms-win-shcore-scaling-l1-1-1.dll" and can't find required file in system32 folder (because Shcore part of windows 8.1, which used for GetDPIForMonitor in AppCore.dll)

Problem happen due to SetProcessDpiAwareness (PROCESS_PER_MONITOR_DPI_AWARE)

This issue happen in Ruffle emulator, we recently updated tinyfiledialogs-rs up to v3.9.0

**Comment by kuviman** [comment]
Probably related, cross compilation to windows seems broken, failing with this error:

```
libtinyfiledialogs/tinyfiledialogs.c:186:29: fatal error: ShellScalingApi.h: No such file or directory
```

because shcore is not available there

previously there was linking issues related to shcore too: https://github.com/jdm/tinyfiledialogs-rs/issues/28

**Comment by macpp** [comment]
Run into analogous issue for unrelated reason - when using windows-gnu target it seems that `ShellScalingApi.h` is missing on mingw compiler (at least on the version that i'm using)
Usage of `ShellScalingApi.h` was added in #25, and it seems that it's absent in upstream liblary. Since it's patch from this repository, i think that it may make sense to add cargo feature for this, so patch can be disabled if unwanted
opened pull request for that: #37
